### ISSUE TITLE
Software/setup page

### ISSUE THREAD

**Issue by k8hertweck** [fredhutchio/fredhutch.io#14]
It would be great to have a separate page that includes links to software used in class along with installation instructions across Mac/Linux/Windows. 

- [x] create page
- [x] R/RStudio installation (can be based on [this](https://datacarpentry.org/R-ecology-lesson/))
- [x] git desktop client ([link](https://desktop.github.com))

**Comment by bcclaywell** [comment]
Software page added in 2e18424.
